# Generated by Django 5.1.6 on 2025-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Live URL or repo link (can be empty)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date_end',
            field=models.DateField(blank=True, help_text='Date you completed the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills used', max_length=200),
        ),
    ]
