# Generated by Django 5.1.6 on 2025-08-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benfolio', '0004_project_image_project_show_on_home_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='small_description',
            field=models.TextField(blank=True, help_text='Small description of the project', null=True),
        ),
    ]
