services:
  - type: web
    name: benfolio
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt && \
      npm ci && npm run sass:build && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate --noinput
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DEBUG
        value: "False"
      # Set the following in Render dashboard or here with generated values
      # - key: SECRET_KEY
      #   generateValue: true
      # - key: DATABASE_URL
      #   fromDatabase: benfolio-db

# Optional: create a managed Postgres separately in the dashboard and link via DATABASE_URL.
